import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';
import vercel from '@astrojs/vercel';

export default defineConfig({
  site: 'https://www.108vision.it',
  output: 'static',
  adapter: vercel(),
  redirects: {
    '/wellbeing-app': '/wellbeing',
    '/en/wellbeing-app': '/en/wellbeing',
    '/ai-platform': '/software-in-mano',
    '/en/ai-platform': '/en/software-in-mano',
    '/trasformazione-digitale': '/software-in-mano',
    '/en/trasformazione-digitale': '/en/software-in-mano',
    '/digital-starter': '/software-in-mano',
    '/en/digital-starter': '/en/software-in-mano',
    '/fractional-cto': '/direzione-tecnica',
    '/en/fractional-cto': '/en/direzione-tecnica',
    '/architettura': '/direzione-tecnica',
    '/en/architettura': '/en/direzione-tecnica',
    '/leadership': '/direzione-tecnica',
    '/en/leadership': '/en/direzione-tecnica',
    '/agile-devops': '/direzione-tecnica',
    '/en/agile-devops': '/en/direzione-tecnica',
    '/tech-wellbeing': '/direzione-tecnica',
    '/en/tech-wellbeing': '/en/direzione-tecnica',
    '/ai-adoption': '/direzione-tecnica',
    '/en/ai-adoption': '/en/direzione-tecnica',
    '/factory': '/software-in-mano',
    '/en/factory': '/en/software-in-mano',
    '/sviluppo-progetto': '/software-in-mano',
    '/en/sviluppo-progetto': '/en/software-in-mano',
    '/sviluppo': '/software-in-mano',
    '/en/sviluppo': '/en/software-in-mano',
    '/chi-sono': '/chi-siamo',
    '/en/chi-sono': '/en/chi-siamo',
    '/pubblica-amministrazione': '/contatti',
    '/en/pubblica-amministrazione': '/en/contatti',
    '/risorse/guida-ai-pmi': '/risorse',
    '/en/risorse/guida-ai-pmi': '/en/risorse',
    '/risorse/guida-architettura': '/risorse',
    '/en/risorse/guida-architettura': '/en/risorse',
    '/risorse/guida-trasformazione-digitale': '/risorse',
    '/en/risorse/guida-trasformazione-digitale': '/en/risorse',
    '/risorse/guida-leadership': '/risorse',
    '/en/risorse/guida-leadership': '/en/risorse',
    '/risorse/guida-agile-devops': '/risorse',
    '/en/risorse/guida-agile-devops': '/en/risorse',
    '/risorse/guida-wellbeing': '/risorse',
    '/en/risorse/guida-wellbeing': '/en/risorse',
    '/risorse/guida-digital-starter': '/risorse',
    '/en/risorse/guida-digital-starter': '/en/risorse',
    '/risorse/guida-sviluppo-progetto': '/risorse',
    '/en/risorse/guida-sviluppo-progetto': '/en/risorse',
    '/risorse/guida-compliance-ai': '/risorse',
    '/en/risorse/guida-compliance-ai': '/en/risorse',
    '/risorse/guida-nocode': '/risorse',
    '/en/risorse/guida-nocode': '/en/risorse',
    '/risorse/guida-data-analytics': '/risorse',
    '/en/risorse/guida-data-analytics': '/en/risorse',
    '/risorse/guida-pa': '/risorse',
    '/en/risorse/guida-pa': '/en/risorse',
  },
  i18n: {
    defaultLocale: 'it',
    locales: ['it', 'en'],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  vite: {
    plugins: [tailwindcss()],
  },
  integrations: [
    sitemap(),
  ],
  markdown: {
    shikiConfig: {
      theme: 'github-dark',
    },
  },
});
